Repository goreleaser/nfpm, pull requests merged in 2020-12, with the labels that each got.

#261 test: Intergate and test rpmpack ghost file fix
  go.mod
  go.sum
  rpm/rpm_test.go
Labels: size/M

#262 fix: ensure nfpm can run on windows and still build correct rpm, deb, and apk packages
  .gitattributes
  .github/workflows/build.yml
  apk/apk.go
  deb/deb.go
  deb/deb_test.go
  go.mod
  go.sum
  internal/files/files.go
  internal/glob/glob.go
  rpm/rpm_test.go
Labels: automerge, bug, size/L

#266 Fix RPM Verify signature: BAD PARAMETERS when installing from a repo, but not a local file
  go.mod
  go.sum
  rpm/rpm_test.go
  testdata/acceptance/keys/test.rpm.repo
  testdata/acceptance/rpm.signed.dockerfile
Labels: size/S

#267 feat: remove deprecated options
  .github/workflows/build.yml
  CONTRIBUTING.md
  Makefile
  acceptance_test.go
  apk/apk_test.go
  cmd/nfpm/main.go
  deb/deb_test.go
  go.mod
  go.sum
  nfpm.go
  nfpm_test.go
  rpm/rpm_test.go
  testdata/acceptance/complex.386.yaml
  testdata/acceptance/complex.yaml
  testdata/acceptance/config-noreplace-old.yaml
  testdata/acceptance/config-noreplace.yaml
  testdata/acceptance/env-var-version.yaml
  testdata/acceptance/gzip.compression.yaml
  testdata/acceptance/lzma.compression.yaml
  testdata/acceptance/min.yaml
  testdata/acceptance/overrides.yaml
  testdata/acceptance/release.rpm.yaml
  testdata/acceptance/rules.deb.yaml
  testdata/acceptance/signed.yaml
  testdata/acceptance/simple.386.yaml
  testdata/acceptance/simple.arm64.yaml
  testdata/acceptance/simple.ppc64le.yaml
  testdata/acceptance/simple.yaml
  testdata/acceptance/symlink.yaml
  testdata/acceptance/triggers.yaml
  testdata/acceptance/withchangelog.yaml
  testdata/acceptance/xz.compression.yaml
  testdata/overrides.yaml
  testdata/versionenv.yaml
Labels: enhancement, size/XL

#268 feat: version as v2
  .golangci.yml
  README.md
  acceptance_test.go
  apk/apk.go
  apk/apk_test.go
  cmd/nfpm/main.go
  deb/deb.go
  deb/deb_test.go
  files/files.go
  files/files_test.go
  go.mod
  internal/sign/pgp.go
  internal/sign/pgp_test.go
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/usage.md
Labels: automerge, enhancement, size/M

#269 feat: more deprecated things to remove
  nfpm.go
  nfpm_test.go
Labels: automerge, enhancement, size/S

#270 feat: update deps
  go.mod
  go.sum
Labels: automerge, enhancement, size/XS

#273 fix: race condition and remove unused code
  files/files.go
  files/files_test.go
  nfpm.go
  testdata/contents.yaml
  www/docs/configuration.md
Labels: automerge, bug, enhancement, size/L

#274 feat: improve docker image
  .goreleaser.yml
  Dockerfile
Labels: enhancement, size/M
