Repository goreleaser/nfpm, pull requests merged in 2020-10, with the labels that each got.

#231 docs: globs
  www/docs/configuration.md
Labels: automerge, size/XS

#234 deps: Update zglob.
  acceptance/testdata/rpm.meta.dockerfile
  go.mod
  go.sum
  internal/glob/glob_test.go
  internal/glob/testdata/{dir_d}/test_brace.txt
Labels: size/XS

#238 fix: Fix hash name typo.
  internal/sign/rsa.go
Labels: size/S
