Repository goreleaser/nfpm, pull requests merged in 2020-11, with the labels that each got.

#240 feat: add support for deb templates
  deb/deb.go
  deb/deb_test.go
  deb/testdata/templates.golden
  nfpm.go
  www/docs/configuration.md
Labels: size/M

#236 chore(ci): dont need to tidy anymore
  .github/workflows/gosum.yml
Labels: automerge, enhancement, size/M

#246 feat: Allow explicit summary from RPM packages
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/M

#244 feat: replace glob library
  acceptance/testdata/complex.386.yaml
  acceptance/testdata/complex.yaml
  acceptance/testdata/overrides.yaml
  apk/apk_test.go
  deb/deb_test.go
  go.mod
  go.sum
  internal/files/files_test.go
  internal/glob/glob.go
  internal/glob/glob_test.go
  rpm/rpm_test.go
Labels: enhancement, size/L

#245 feat: Support RPM ghost files
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/M

#247 refactor: simplify rpm add file
  rpm/rpm.go
Labels: automerge, enhancement, size/S

#248 feat: Add option to disable globbing
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  internal/files/files.go
  internal/files/files_test.go
  internal/glob/glob.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/{file}*
  www/docs/configuration.md
Labels: size/L

#251 chore(deps): bump github.com/golangci/golangci-lint from 1.31.0 to 1.32.2
  .golangci.yml
  apk/apk_test.go
  deb/deb_test.go
  go.mod
  go.sum
  internal/files/files.go
  internal/glob/glob_test.go
  rpm/rpm_test.go
Labels: enhancement, size/M

#253 fix: invalid zip file
  apk/apk_test.go
  deb/deb_test.go
  internal/files/files_test.go
  rpm/rpm_test.go
  testdata/{file}[
Labels: bug

#233 test: Add APK and RSA sign test
  apk/apk_test.go
  internal/sign/rsa.go
  internal/sign/rsa_test.go
  internal/sign/testdata/wrong_key_format.priv
  internal/sign/testdata/wrong_key_format.pub
Labels: size/L
