Repository goreleaser/nfpm, pull requests merged in 2020-09, with the labels that each got.

#220 feat: Support DEB Breaks field
  Makefile
  acceptance/acceptance_test.go
  acceptance/testdata/breaks.yaml
  acceptance/testdata/deb.breaks.dockerfile
  acceptance/testdata/dummy.deb
  deb/deb.go
  nfpm.go
  www/docs/configuration.md
Labels: automerge, enhancement

#223 fix: Change upgrade to update in changelog dockerfile
  acceptance/testdata/deb.changelog.dockerfile
Labels: size/XS

#224 feat(#212): Package Signing
  acceptance/acceptance_test.go
  acceptance/testdata/apk.signed.dockerfile
  acceptance/testdata/deb.signed.dockerfile
  acceptance/testdata/keys/pubkey.asc
  acceptance/testdata/keys/pubkey.gpg
  acceptance/testdata/keys/rsa_unprotected.pub
  acceptance/testdata/rpm.signed.dockerfile
  acceptance/testdata/signed.yaml
  apk/apk.go
  apk/apk_test.go
  apk/testdata/TestControl.golden
  apk/testdata/TestCreateBuilderControl.golden
  apk/testdata/TestCreateBuilderControlScripts.golden
  deb/deb.go
  deb/deb_test.go
  go.mod
  go.sum
  internal/sign/pgp.go
  internal/sign/pgp_test.go
  internal/sign/rsa.go
  internal/sign/rsa_test.go
  internal/sign/testdata/multiple_privkeys.asc
  internal/sign/testdata/privkey.asc
  internal/sign/testdata/privkey.gpg
  internal/sign/testdata/privkey_unprotected.asc
  internal/sign/testdata/privkey_unprotected.gpg
  internal/sign/testdata/pubkey.asc
  internal/sign/testdata/pubkey.gpg
  internal/sign/testdata/rsa.priv
  internal/sign/testdata/rsa.pub
  internal/sign/testdata/rsa_unprotected.priv
  internal/sign/testdata/rsa_unprotected.pub
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: automerge, enhancement

#227 Deps: Use upstream rpmpack.
  go.mod
  go.sum
Labels: size/XS

#226 refactor: remove pkg/errors
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  go.mod
  internal/glob/glob.go
  internal/glob/glob_test.go
  internal/sign/pgp.go
  internal/sign/rsa.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: size/L

#230 fix: auto-commit go mod tidy
  .github/workflows/gosum.yml
Labels: enhancement, size/S
