Repository goreleaser/nfpm, pull requests merged in 2020-07, with the labels that each got.

#152 fix rpm recommends
  acceptance/testdata/complex.yaml
  acceptance/testdata/rpm.complex.dockerfile
  rpm/rpm.go
Labels: size/S

#153 test: pkg dependencies
  acceptance/testdata/deb.complex.dockerfile
  acceptance/testdata/rpm.complex.dockerfile
Labels: enhancement, size/XS

#156 Feature(RPM): Allow platform independet packages by translating arch "all" to "noarch" for RPM packages
  rpm/rpm.go
Labels: size/XS

#160 feat: update rpmpack
  go.mod
  go.sum
Labels: enhancement, size/XS

#157 WIP: feat: Use conventional file names by default
  cmd/nfpm/main.go
  deb/deb.go
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
Labels: size/M

#163 fix: Fix wrong separator in conventional RPM file name.
  rpm/rpm.go
Labels: size/XS

#159 feat: allow creating meta packages
  acceptance/acceptance_test.go
  acceptance/testdata/deb.meta.dockerfile
  acceptance/testdata/meta.yaml
  acceptance/testdata/rpm.meta.dockerfile
  cmd/nfpm/main.go
  go.mod
  go.sum
  nfpm.go
  nfpm_test.go
Labels: enhancement, size/M

#166 docs: update contributing.md
  CONTRIBUTING.md
  www/docs/install.md
Labels: enhancement, size/XS

#158 feat(#42): Support Changelogs
  acceptance/acceptance_test.go
  acceptance/testdata/deb.changelog.dockerfile
  acceptance/testdata/rpm.changelog.dockerfile
  acceptance/testdata/withchangelog.yaml
  cmd/nfpm/main.go
  deb/deb.go
  deb/deb_test.go
  go.mod
  go.sum
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/changelog.yaml
  www/docs/configuration.md
Labels: automerge, size/L

#169 fix: Improve changelog formatting.
  acceptance/testdata/rpm.changelog.dockerfile
  deb/deb.go
  deb/deb_test.go
  rpm/rpm.go
Labels: size/M

#170 fix: Reflect (pre)release in conventional file names.
  deb/deb.go
  deb/deb_test.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: size/M

#180 test(#132): Add tests with symlinked files.
  deb/deb_test.go
  rpm/rpm_test.go
Labels: size/L

#178 feat: Add support for DEB triggers.
  acceptance/acceptance_test.go
  acceptance/testdata/deb.triggers.dockerfile
  acceptance/testdata/scripts/postinstall_trigger.sh
  acceptance/testdata/triggers.yaml
  deb/deb.go
  deb/deb_test.go
  nfpm.go
  www/docs/configuration.md
Labels: size/L

#182 chore(ci): run fast tests first
  Makefile
  acceptance/acceptance_test.go
Labels: enhancement, size/S

#185 feat(#183): Support symlinks for deb and rpm.
  acceptance/acceptance_test.go
  acceptance/testdata/deb.symlink.dockerfile
  acceptance/testdata/rpm.symlink.dockerfile
  acceptance/testdata/symlink.yaml
  cmd/nfpm/main.go
  deb/deb.go
  deb/deb_test.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/L

#187 fix(#130): Don't propagate semver metadata into deb metadata.
  acceptance/testdata/deb.env-var-version.dockerfile
  nfpm.go
  nfpm_test.go
  www/docs/configuration.md
Labels: size/XS

#188 test: Reuse rpm tag constants from rpmutils.
  rpm/rpm_test.go
Labels: size/M
