Repository goreleaser/nfpm, pull requests merged in 2020-08, with the labels that each got.

#179 fix: Avoid panic if target is blank/dir and no packager is specified.
  cmd/nfpm/main.go
Labels: size/S

#191 refactor: internal/files
  deb/deb.go
  go.mod
  go.sum
  internal/files/files.go
  internal/files/files_test.go
  internal/helpers/helpers.go
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
Labels: enhancement, size/L

#186 feat(#129): Support RPM %config(noreplace) files.
  acceptance/acceptance_test.go
  acceptance/testdata/config-noreplace-old.yaml
  acceptance/testdata/config-noreplace.yaml
  acceptance/testdata/rpm.config-noreplace.dockerfile
  deb/deb.go
  go.mod
  go.sum
  internal/files/files.go
  internal/files/files_test.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/whatever2.conf
  www/docs/configuration.md
Labels: size/L

#195 test: Changed some asserts to requires for early out in tests.
  deb/deb_test.go
  nfpm_test.go
  rpm/rpm_test.go
Labels: automerge, enhancement, size/L

#197 fix: Remove RPM group default.
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: automerge, enhancement, size/M

#208 ci: make acceptance test logs more readable
  acceptance/acceptance_test.go
Labels: enhancement, size/M

#209 fix: Remove leading slashes from files in .tag.gz files in deb.
  deb/deb.go
  deb/deb_test.go
Labels: size/M

#211 fix: Fix build badge and coverage format.
  Makefile
  README.md
Labels: size/XS

#213 docs: Give overrides examples for depends with version constraints.
  www/docs/configuration.md
Labels: size/XS

#214 fix: Correctly handle version, release and prerelease for RPMs.
  acceptance/testdata/rpm.env-var-version.dockerfile
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: size/M

#215 feat: Introduce version_metadata for all packagers (deprecate deb.metadata)
  acceptance/testdata/apk.env-var-version.dockerfile
  acceptance/testdata/deb.env-var-version.dockerfile
  acceptance/testdata/rpm.env-var-version.dockerfile
  apk/apk.go
  deb/deb.go
  deb/deb_test.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/L

#218 Fix: Fix deb file path prefixes and md5sums file
  acceptance/testdata/deb.changelog.dockerfile
  deb/deb.go
  deb/deb_test.go
Labels: size/L
