Repository goreleaser/nfpm, pull requests merged in 2021-02, with the labels that each got.

#291 fix: add the PAXHeaders for file checksum required by alpine 3.13+
  Makefile
  acceptance_test.go
  apk/apk.go
  apk/apk_test.go
  go.mod
  go.sum
  testdata/acceptance/apk.386.complex.dockerfile
  testdata/acceptance/apk.386.dockerfile
  testdata/acceptance/apk.arm64.dockerfile
  testdata/acceptance/apk.changelog.dockerfile
  testdata/acceptance/apk.complex.dockerfile
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/apk.env-var-version.dockerfile
  testdata/acceptance/apk.meta.dockerfile
  testdata/acceptance/apk.min.dockerfile
  testdata/acceptance/apk.overrides.dockerfile
  testdata/acceptance/apk.ppc64le.dockerfile
  testdata/acceptance/apk.signed.dockerfile
  testdata/acceptance/apk.symlink.dockerfile
Labels: size/M

#295 fix: apk checksums
  apk/apk.go
  apk/apk_test.go
  go.sum
Labels: automerge, bug, size/M

#297 Don't override mode/mtime file information if already set
  files/files.go
  files/files_test.go
Labels: size/M

#303 fix: Fix file collision detection with per-file packagers
  files/files.go
  files/files_test.go
Labels: automerge, bug, size/M

#304 feat(ci): lint action, gocenter, tools
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  acceptance_test.go
  apk/apk.go
  apk/apk_test.go
  cmd/nfpm/main.go
  deb/deb.go
  deb/deb_test.go
  files/files_test.go
  go.mod
  go.sum
  internal/sign/pgp.go
  internal/sign/rsa.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  tools.go
Labels: automerge, enhancement, size/L
