Repository goreleaser/nfpm, pull requests merged in 2021-11, with the labels that each got.

#396 Feature: Allow platform specific arch overrides.
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  nfpm.go
  rpm/rpm.go
  www/docs/configuration.md
Labels: size/M

#395 Fix: Allow complex file modes for debs and apks.
  apk/apk.go
  deb/deb.go
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/rpm.dockerfile
  www/docs/configuration.md
Labels: size/S

#394 Fix build task.
  Taskfile.yml
Labels: size/XS

#391 fix docker exec example
  www/docs/install.md
Labels: size/XS

#388 Fix: Improve performance of content destination collision detection.
  files/files.go
  internal/cmd/package.go
  nfpm.go
  nfpm_test.go
Labels: size/M

#397 refactor: improve if a bit
  apk/apk.go
  deb/deb.go
  rpm/rpm.go
Labels: enhancement, size/M

#398 fix: added more arches
  apk/apk.go
  apk/apk_test.go
  deb/deb_test.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: enhancement, size/L

#390 feat: Directory content type with custom attributes
  acceptance_test.go
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  files/files.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/acceptance/rpm.directories.yaml
  testdata/acceptance/rpm.dockerfile
  www/docs/configuration.md
Labels: size/XL

#400 feat: rename branch to main
  .github/ISSUE_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/lock.yml
  CONTRIBUTING.md
  README.md
  www/docs/contributing.md
  www/docs/usage.md
  www/mkdocs.yml
Labels: size/S

#399 feat: add deprecation notice interface
  deb/deb.go
  deprecation/deprecation.go
  deprecation/deprecation_test.go
  nfpm.go
Labels: enhancement, size/M

#406 feat: expand-env support for vendor field
  nfpm.go
  nfpm_test.go
  www/docs/configuration.md
Labels: size/S

#408 chore(ci): use major cache action version
  .github/workflows/build.yml
Labels: size/XS

#409 feat: custom packager configuration for rpm pkg
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/M
