Repository goreleaser/nfpm, pull requests merged in 2021-04, with the labels that each got.

#315 fix: switch to use gopenpgp
  deb/deb.go
  go.mod
  go.sum
  internal/sign/pgp.go
  internal/sign/pgp_test.go
  internal/sign/testdata/privkey_unprotected_subkey_only.asc
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/acceptance/deb.signed.dockerfile
  testdata/acceptance/rpm.signed.dockerfile
  testdata/acceptance/signed.yaml
  www/docs/configuration.md
Labels: size/L

#318 docs: add a tip and hints page
  www/docs/tips.md
  www/mkdocs.yml
Labels: size/L

#317 feat: Support for deb's config maintenance script
  deb/deb.go
  nfpm.go
  testdata/acceptance/rules.deb.yaml
  testdata/acceptance/scripts/config
  testdata/acceptance/scripts/templates
  www/docs/configuration.md
Labels: automerge, size/S

#319 feat: gomod verifiable builds
  .goreleaser.yml
  cmd/nfpm/main.go
Labels: enhancement, size/S

#321 fix: split the workflows by platform as well
  .github/workflows/build.yml
Labels: size/S

#322 feat: add %pretrans %posttrans scriptlets
  go.mod
  go.sum
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/rpm.dockerfile
  testdata/acceptance/scripts/posttrans.sh
  testdata/acceptance/scripts/pretrans.sh
  testdata/scripts/posttrans.sh
  testdata/scripts/pretrans.sh
  www/docs/configuration.md
  www/docs/tips.md
Labels: automerge, enhancement, size/M

#324 feat: add version_schema config option to allow controlling how the version string is parsed.
  nfpm.go
  nfpm_test.go
  www/docs/configuration.md
Labels: automerge, enhancement, size/M

#325 feat: overhaul cmd and release process
  .gitignore
  .goreleaser.yml
  Dockerfile
  README.md
  cmd/nfpm/main.go
  go.mod
  go.sum
  internal/cmd/completion.go
  internal/cmd/completion_test.go
  internal/cmd/doc.go
  internal/cmd/docs.go
  internal/cmd/init.go
  internal/cmd/package.go
  internal/cmd/root.go
  scripts/cmd_docs.sh
  scripts/completions.sh
  www/docs/cmd/nfpm.md
  www/docs/cmd/nfpm_completion.md
  www/docs/cmd/nfpm_init.md
  www/docs/cmd/nfpm_package.md
  www/docs/index.md
  www/docs/install.md
  www/docs/sponsors.md
  www/docs/usage.md
  www/mkdocs.yml
Labels: automerge, enhancement, size/XL
