Repository goreleaser/nfpm, pull requests merged in 2021-01, with the labels that each got.

#282 fix: allow using an env var in the signature.key_file field
  nfpm.go
  nfpm_test.go
  testdata/env-fields.yaml
  www/docs/configuration.md
Labels: size/M

#287 fix: set the alpine linux version to v3.12 so the acceptance tests pass
  testdata/acceptance/apk.386.complex.dockerfile
  testdata/acceptance/apk.386.dockerfile
  testdata/acceptance/apk.arm64.dockerfile
  testdata/acceptance/apk.changelog.dockerfile
  testdata/acceptance/apk.complex.dockerfile
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/apk.env-var-version.dockerfile
  testdata/acceptance/apk.meta.dockerfile
  testdata/acceptance/apk.min.dockerfile
  testdata/acceptance/apk.overrides.dockerfile
  testdata/acceptance/apk.ppc64le.dockerfile
  testdata/acceptance/apk.signed.dockerfile
  testdata/acceptance/apk.symlink.dockerfile
Labels: automerge, size/S

#290 fix: Prevent destination collisions
  files/files.go
  files/files_test.go
  go.sum
  www/docs/configuration.md
Labels: automerge, size/M
