Repository goreleaser/nfpm, pull requests merged in 2021-12, with the labels that each got.

#411 fix: Prevent duplicate folders from being created.
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  files/files.go
Labels: size/L

#410 fix: Fix destinations for files containing matchers when globbing is disabled.
  files/files.go
  files/files_test.go
  files/testdata/{test}/[f]oo
  files/testdata/{test}/bar
  internal/glob/glob.go
  internal/glob/glob_test.go
Labels: size/M

#412 fix: deb on arm5 and arm6
  deb/deb.go
Labels: size/XS

#414 fix: disable debian arm6 tests
  acceptance_test.go
Labels: bug, size/XS

#421 chore(Taskfile): Remove -s flag for gofumpt
  Taskfile.yml
Labels: size/XS

#431 fix: create tree of dir content types
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  rpm/rpm_test.go
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/rpm.dockerfile
Labels: bug, size/L
