Repository goreleaser/nfpm, pull requests merged in 2022-12, with the labels that each got.

#584 docs: Discourage "v" prefix for version numbers
  www/docs/configuration.md
Labels: size/XS

#588 fixes minor typos
  www/docs/configuration.md
Labels: size/M

#595 docs: remove vercel deploy
  Taskfile.yml
  scripts/vercel/build.sh
  scripts/vercel/install.sh
  vercel.json
Labels: enhancement, size/S

#593 Fix expansion of env vars in non-overriden package relation fields
  nfpm.go
Labels: size/XS

#596 fix: do not encourage using /usr/local/bin
  apk/apk_test.go
  arch/arch_test.go
  deb/deb_test.go
  internal/cmd/init.go
  internal/rpmpack/rpm_test.go
  rpm/rpm_test.go
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/archlinux.dockerfile
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/core.env-var-version.yaml
  testdata/acceptance/core.min.yaml
  testdata/acceptance/core.overrides.yaml
  testdata/acceptance/core.signed.yaml
  testdata/acceptance/core.simple.yaml
  testdata/acceptance/core.withchangelog.yaml
  testdata/acceptance/deb.debsign.sign.yaml
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/deb.dpkg-sig.sign.yaml
  testdata/acceptance/deb.gzip.compression.yaml
  testdata/acceptance/deb.none.compression.yaml
  testdata/acceptance/deb.rules.yaml
  testdata/acceptance/deb.triggers.yaml
  testdata/acceptance/deb.xz.compression.yaml
  testdata/acceptance/rpm.dockerfile
  testdata/acceptance/rpm.gzip.compression.yaml
  testdata/acceptance/rpm.lzma.compression.yaml
  testdata/acceptance/rpm.release.yaml
  testdata/acceptance/rpm.xz.compression.yaml
  www/docs/configuration.md
Labels: enhancement, size/L

#597 fix(deb): changelog fixes
  deb/deb.go
  deb/deb_test.go
  testdata/acceptance/deb.dockerfile
Labels: bug, size/M
