Repository goreleaser/nfpm, pull requests merged in 2022-05, with the labels that each got.

#506 feat(deps): switch back to cobra
  go.mod
  go.sum
  internal/cmd/docs.go
  internal/cmd/init.go
  internal/cmd/man.go
  internal/cmd/package.go
  internal/cmd/root.go
  internal/cmd/schema.go
Labels: enhancement, size/M

#485 docs: remove analytics
  www/docs/overrides/partials/integrations/analytics.html
  www/mkdocs.yml
Labels: size/XS

#483 feat: use go 1.18
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .golangci.yml
  CONTRIBUTING.md
  go.mod
  go.sum
Labels: enhancement, size/S

#512 Fix typo on 'package' commands --help
  internal/cmd/package.go
Labels: size/XS

#508 feat: implement dpkg-sig Package signing
  deb/deb.go
  deb/deb_test.go
  internal/sign/pgp.go
  nfpm.go
Labels: enhancement, size/L
