Repository goreleaser/nfpm, pull requests merged in 2022-09, with the labels that each got.

#544 fix: govulncheck, semgrep & ruleguard scan/fixes
  .github/workflows/build.yml
  .github/workflows/lint.yml
  apk/apk.go
  deb/deb.go
  internal/glob/glob.go
  nfpm.go
  nfpm_test.go
Labels: enhancement, size/M

#547 fix: fish completions path on nfpm
  .goreleaser.yml
Labels: bug, size/XS

#549 Fix post-remove script example
  www/docs/tips.md
Labels: size/M

#548 feat: allow env expansion in conflicts, suggests, recommends, depends…
  go.mod
  go.sum
  internal/rpmpack/LICENSE
  internal/rpmpack/dir.go
  internal/rpmpack/dir_test.go
  internal/rpmpack/file_types.go
  internal/rpmpack/file_types_test.go
  internal/rpmpack/header.go
  internal/rpmpack/header_test.go
  internal/rpmpack/rpm.go
  internal/rpmpack/rpm_test.go
  internal/rpmpack/sense.go
  internal/rpmpack/sense_test.go
  internal/rpmpack/tags.go
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  testdata/acceptance/core.overrides.yaml
  www/docs/configuration.md
Labels: size/XXL

#550 chore: improving ci config
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/lock.yml
  .github/workflows/milestone.yml
  .github/workflows/release.yml
Labels: enhancement, size/L

#554 fix: dont modify slices in a loop
  nfpm.go
  nfpm_test.go
Labels: size/S
