Repository goreleaser/nfpm, pull requests merged in 2022-10, with the labels that each got.

#559 feat: allow to parse from stdin
  nfpm.go
Labels: enhancement, size/XS

#543 feat: add support for Arch Linux packages
  .github/workflows/build.yml
  acceptance_test.go
  apk/apk.go
  arch/arch.go
  arch/arch_test.go
  deb/deb.go
  internal/cmd/package.go
  internal/cmd/root.go
  nfpm.go
  rpm/rpm.go
  testdata/acceptance/archlinux.dockerfile
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/core.overrides.yaml
  testdata/acceptance/upgrade.v1.yaml
  testdata/acceptance/upgrade.v2.yaml
  www/docs/cmd/nfpm_package.md
  www/docs/configuration.md
  www/docs/index.md
Labels: enhancement, size/XXL

#568 Allow using directories as contents in archlinux packager
  arch/arch.go
  arch/arch_test.go
  testdata/acceptance/apk.dockerfile
  testdata/acceptance/archlinux.dockerfile
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/rpm.dockerfile
  testdata/something/a
  testdata/something/b
  testdata/something/c/d
Labels: size/M
