Repository goreleaser/nfpm, pull requests merged in 2022-02, with the labels that each got.

#438 fix: deb multilines should have 1 space prefix
  deb/deb.go
  deb/testdata/multiline.golden
Labels: bug

#442 feat: migrate to coral
  go.mod
  go.sum
  internal/cmd/docs.go
  internal/cmd/init.go
  internal/cmd/package.go
  internal/cmd/root.go
  internal/cmd/schema.go
Labels: size/M

#443 feat: generate man pages
  .gitignore
  .goreleaser.yml
  go.mod
  go.sum
  internal/cmd/man.go
  internal/cmd/root.go
  scripts/manpages.sh
Labels: enhancement, size/M

#444 feat: publish to aur
  .github/workflows/build.yml
  .goreleaser.yml
Labels: enhancement, size/S

#447 feat: bump mango
  go.mod
  go.sum
Labels: bug, size/XS

#446 fix: vendor is not a recognized deb control field
  deb/deb.go
  deb/testdata/control.golden
  deb/testdata/control2.golden
Labels: bug, size/XS

#454 Expand dependencies' version
  nfpm.go
  nfpm_test.go
Labels: size/S

#458 fix: update rpmpack and change default compressor to gzip:-1 (a default level) instead of gzip:9
  go.mod
  go.sum
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: enhancement, size/M

#457 feat: replace compress/gzip by klauspost/pgzip
  apk/apk.go
  deb/deb.go
  go.mod
  go.sum
Labels: size/XS

#462 style: spelling and grammar fixes
  CONTRIBUTING.md
  apk/apk.go
  internal/sign/pgp.go
  nfpm.go
  rpm/rpm.go
  www/docs/configuration.md
  www/docs/index.md
  www/docs/install.md
Labels: size/S
