Repository goreleaser/nfpm, pull requests merged in 2023-07, with the labels that each got.

#688 feat: unfork rpmpack.
  go.mod
  go.sum
  internal/rpmpack/LICENSE
  internal/rpmpack/dir.go
  internal/rpmpack/dir_test.go
  internal/rpmpack/file_types.go
  internal/rpmpack/file_types_test.go
  internal/rpmpack/header.go
  internal/rpmpack/header_test.go
  internal/rpmpack/rpm.go
  internal/rpmpack/rpm_test.go
  internal/rpmpack/sense.go
  internal/rpmpack/sense_test.go
  internal/rpmpack/tags.go
  rpm/rpm.go
Labels: size/XXL

#692 build: pkg on windows, install on linux
  .github/workflows/build.yml
Labels: enhancement, size/M

#691 feat(rpm): support relocatable packages
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/acceptance/core.complex.yaml
  testdata/acceptance/rpm.dockerfile
  www/docs/configuration.md
Labels: enhancement

#690 fix: windows
  apk/apk.go
  arch/arch.go
  deb/deb.go
  files/files.go
  files/files_test.go
  internal/glob/glob.go
  internal/glob/glob_test.go
  rpm/rpm.go
Labels: bug, enhancement, size/M

#675 feat: expand env variables in homepage field
  nfpm.go
  nfpm_test.go
  www/docs/configuration.md
Labels: size/S

#693 docs: improve deb fields var expansion example
  nfpm_test.go
  www/docs/configuration.md
Labels: size/S
