Repository goreleaser/nfpm, pull requests merged in 2023-06, with the labels that each got.

#669 fix(golangci-lint): depguard (v2) config for >= 1.53
  .golangci.yml
Labels: size/XS

#668 feat: completion improvements
  internal/cmd/docs.go
  internal/cmd/init.go
  internal/cmd/man.go
  internal/cmd/package.go
  internal/cmd/root.go
  internal/cmd/schema.go
Labels: size/M

#667 feat: expand environment variables in deb fields values
  nfpm.go
  nfpm_test.go
  www/docs/configuration.md
Labels: size/S

#674 chore: remove space from asset name
  .goreleaser.yml
Labels: size/XS

#678 test: signatures on centos 7 and 8
  .gitignore
  acceptance_test.go
  testdata/acceptance/rpm_centos8.dockerfile
  testdata/acceptance/rpm_centos9.dockerfile
Labels: enhancement, size/M

#684 fix: version output
  cmd/nfpm/main.go
Labels: size/XS

#685 fix: use goversion lib
  .goreleaser.yml
  README.md
  cmd/nfpm/art.txt
  cmd/nfpm/main.go
  go.mod
  go.sum
  internal/cmd/root.go
Labels: enhancement, size/M
