Repository goreleaser/nfpm, pull requests merged in 2023-02, with the labels that each got.

#613 Revert "feat(deps): bump github.com/ProtonMail/gopenpgp/v2 from 2.5.1 to 2.5.2"
  go.mod
  go.sum
Labels: size/S

#615 fix: dependency tree
  go.mod
  go.sum
Labels: bug, dependencies, size/L

#618 feat: Refactor contents handling and add tree content type.
  apk/apk.go
  apk/apk_test.go
  arch/arch.go
  arch/arch_test.go
  deb/deb.go
  deb/deb_test.go
  deb/testdata/minimal.golden
  deb/testdata/rules.golden
  files/files.go
  files/files_test.go
  files/testdata/tree/files/a
  files/testdata/tree/files/b/c
  files/testdata/tree/symlinks/link1
  files/testdata/tree/symlinks/link2
  nfpm.go
  nfpm_test.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/XXL

#624 feat: upgrade go
  .github/workflows/build.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: enhancement, size/S
