Repository goreleaser/nfpm, pull requests merged in 2023-08, with the labels that each got.

#695 feat: Add support for remote signing keys
  apk/apk.go
  apk/apk_test.go
  deb/deb.go
  deb/deb_test.go
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
Labels: enhancement, size/L

#696 feat: add minimal support for Debian pre-dependencies
  deb/deb.go
  deb/deb_test.go
  deb/testdata/bad_provides.golden
  deb/testdata/control.golden
  nfpm.go
  www/docs/configuration.md
Labels: enhancement, size/S

#699 test: deb.predepends integration test
  acceptance_test.go
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/deb.predepends.yaml
Labels: size/S
