Repository goreleaser/nfpm, pull requests merged in 2023-01, with the labels that each got.

#601 feat: expand variables in platform field
  apk/apk.go
  apk/apk_test.go
  arch/arch.go
  arch/arch_test.go
  deb/deb.go
  deb/deb_test.go
  nfpm.go
  nfpm_test.go
  rpm/rpm_test.go
  www/docs/configuration.md
Labels: size/L

#602 test: improve test code
  apk/apk_test.go
  arch/arch_test.go
  deb/deb_test.go
  nfpm_test.go
  rpm/rpm_test.go
Labels: enhancement, size/M

#606 fix(deb): do not allow empty items in deb.provides
  deb/deb.go
  deb/deb_test.go
  deb/testdata/bad_provides.golden
Labels: bug, size/M

#611 feat: add zstd compression support for deb and rpm
  acceptance_test.go
  deb/deb.go
  deb/deb_test.go
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/deb.zstd.compression.yaml
  testdata/acceptance/rpm.zstd.compression.yaml
  www/docs/configuration.md
Labels: size/M
