Repository goreleaser/nfpm, pull requests merged in 2023-12, with the labels that each got.

#747 fix: Ensure reproducable Deb package
  deb/deb.go
Labels: size/S

#753 test: testifylint fixes
  .golangci.yml
  apk/apk_test.go
  deb/deb_test.go
  files/files_test.go
  internal/sign/pgp_test.go
  nfpm_test.go
  rpm/rpm_test.go
Labels: enhancement, size/M

#754 fix: use parent owner/group on typedir
  files/files.go
  files/files_test.go
Labels: bug, size/M

#758 fix: modtime
  arch/arch.go
  deb/deb.go
  internal/modtime/mtime.go
  nfpm.go
  rpm/rpm.go
Labels: bug, size/M

#761 build: use nix flake
  .envrc
  .github/workflows/docs.yml
  .gitignore
  Taskfile.yml
  flake.lock
  flake.nix
  shell.nix
  www/docs/install.md
  www/docs/tips.md
Labels: size/L
