Repository goreleaser/nfpm, pull requests merged in 2024-07, with the labels that each got.

#834 fix: better handle files owned by the fs
  files/files.go
  files/files_test.go
  files/fs.go
  files/testdata/issue829/etc/logrotate.d/acme
  files/testdata/issue829/etc/sysconfig/acme
  files/testdata/issue829/lib/systemd/system/acme.service
  files/testdata/issue829/usr/share/doc/acme/readme.md
  files/testdata/issue829/usr/share/man/man1/acme.1.gz
  files/testdata/issue829/var/log/acme/.gitkeep
Labels: bug, size/M

#836 fix: rpm doesnt allow dashes in prerelease
  rpm/rpm.go
  rpm/rpm_test.go
Labels: bug

#837 test: centos8 mirrorlist has been down for a long time
  acceptance_test.go
  testdata/acceptance/rpm_centos8.dockerfile
Labels: bug, size/S

#838 fix: system fs paths on windows
  files/fs.go
Labels: size/XS

#841 fix(deb): dpkg-sig format
  deb/deb.go
  deb/deb_test.go
  internal/sign/pgp.go
Labels: size/L
