Repository goreleaser/nfpm, pull requests merged in 2024-03, with the labels that each got.

#794 fix(apk): conventional name template
  apk/apk.go
  apk/apk_test.go
  apk/testdata/TestControl.golden
  apk/testdata/TestCreateBuilderControl.golden
  apk/testdata/TestCreateBuilderControlScripts.golden
Labels: bug, size/M

#802 add s390x support
  .goreleaser.yml
Labels: size/XS

#804 feat: support PKCS8 keys for APK signing
  internal/sign/rsa.go
  internal/sign/rsa_test.go
  internal/sign/testdata/rsa_pkcs8.priv
  internal/sign/testdata/rsa_pkcs8.pub
Labels: enhancement, size/L

#808 fix(apk): always append .rsa.pub to key name
  apk/apk.go
  apk/apk_test.go
Labels: size/S
