Repository goreleaser/nfpm, pull requests merged in 2024-01, with the labels that each got.

#760 fix: properly handle files owned by fs
  files/files.go
  files/files_test.go
  files/fs.go
Labels: bug, size/L

#764 fix: update go-rpmutils
  go.mod
  go.sum
Labels: dependencies, size/S

#775 fix: Honor SOURCE_DATE_EPOCH for files
  files/files.go
  files/files_test.go
Labels: bug, size/XS

#779 fix: file mode when type: tree
  files/files.go
  files/files_test.go
Labels: bug, size/M
