Repository goreleaser/nfpm, pull requests merged in 2025-03, with the labels that each got.

#914 feat: Add BuildHost option to RPM packages
  nfpm.go
  rpm/rpm.go
  rpm/rpm_test.go
  www/docs/configuration.md
  www/docs/static/schema.json
Labels: size/S

#916 fix typo in goarch-to-pkg.md
  www/docs/goarch-to-pkg.md
Labels: size/XS

#922 fix: lint issues, modernize codebase
  .golangci.yml
  arch/arch.go
  deb/deb.go
  deprecation/deprecation.go
  files/files.go
  files/files_test.go
  files/fs.go
  internal/glob/glob.go
  internal/glob/glob_test.go
  internal/sign/pgp.go
  ipk/ipk_test.go
  nfpm.go
  nfpm_test.go
  rpm/rpm_test.go
Labels: enhancement, size/L
