Repository goreleaser/nfpm, pull requests merged in 2025-01, with the labels that each got.

#896 fix: aur sources archive content
  .goreleaser.yml
Labels: size/XS

#882 ci: release metadata
  .goreleaser.yml
Labels: size/M

#899 test: test centos10, fedora 40+
  acceptance_test.go
  go.mod
  go.sum
  internal/sign/pgp.go
  testdata/acceptance/rpm_centos10.dockerfile
  testdata/acceptance/rpm_centos9.dockerfile
  testdata/acceptance/rpm_fedora40.dockerfile
  testdata/acceptance/rpm_fedora41.dockerfile
Labels: bug, size/M
