Repository goreleaser/nfpm, pull requests merged in 2025-06, with the labels that each got.

#935 feat: srpm
  rpm/rpm.go
  rpm/rpm_test.go
  testdata/acceptance/deb.dockerfile
  testdata/acceptance/rpm.dockerfile
Labels: enhancement, size/L

#942 refactor: use stdlib maps
  go.mod
  internal/maps/maps.go
Labels: size/S

#945 Corrected amd64 name for deb in goarch-to-pkg.md
  www/docs/goarch-to-pkg.md
Labels: size/XS
